services:
  book-service:
    build:
      context: .
    env_file: .env
    depends_on:
      - book-service-db
    ports:
      - 8082:8082

  book-service-db:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=${BOOK_DB_POSTGRES_DB_NAME}
      - POSTGRES_USER=${BOOK_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BOOK_DB_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - book-db-data:/var/lib/postgresql/data

volumes:
  book-db-data:
